### ISSUE TITLE
Add other README badges

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-go-client#18]
Like: https://github.com/casbin/casbin

![image](https://user-images.githubusercontent.com/3787410/144754016-ed142f23-2eea-4263-8fd8-c21c761aee3f.png)

**Comment by hsluoyz** [comment]
@devajithvs can you also work on this issue?

**Comment by devajithvs** [comment]
Sure. I will work on this. Thanks :)

**Comment by devajithvs** [comment]
@hsluoyz Should I make another PR adding the Coverage badge?

**Comment by hsluoyz** [comment]
@devajithvs sounds good to me!
