### ISSUE TITLE
Usage in mobile or web app

### ISSUE THREAD

**Issue by gedw99** [casbin/casbin-go-client#20]
Is this intended to be used inside the gui app ?

it imports **casbin** server github.com/casbin/casbin-server/proto in order to get the protobuf generated GRPC .
It might be better to create a repo called **casbin-shared** and have the protobufs and generated code that repo. 
then client and server can import this new repo to get the protobuf generated GRPC.

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @nodece @sagilio

**Comment by hsluoyz** [comment]
@tangyang9464 @abichinger @jalinwang @imp2002

**Comment by hsluoyz** [comment]
@xuyukeviki @Makonike @roobtyan @imp2002 can anyone work on this?

**Comment by JalinWang** [comment]
It seems that we don't have many services and there is no need to maintain a separate repo for storing proto IDL files. 🤔

**Comment by hsluoyz** [comment]
Resolved.

**Comment by gedw99** [comment]
Understood and I agree it’s best to keep it all together on 1 repo.
