### ISSUE TITLE
[bug] CI has error: The engine "node" is incompatible with this module. Expected version ">=20.8.1". Got "18.20.4"

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-go-client#25]
See: https://github.com/casbin/casbin-go-client/actions/runs/11189110788/job/31109024568

![image](https://github.com/user-attachments/assets/f1c43993-222b-469f-9c2c-b4945b449c91)

**Comment by hsluoyz** [comment]
@ali-shokoohi can you fix this issue?

**Comment by hsluoyz** [comment]
@ali-shokoohi still error: https://github.com/casbin/casbin-go-client/actions/runs/11191893534/job/31115381958

Can you take a look? You can fork this repo and test the semantic-release on your side to see if your fix actually works before making PR

**Comment by ali-shokoohi** [comment]
You're right @hsluoyz .
Now I merged my changes in my fork and tested it.
https://github.com/ali-shokoohi/casbin-go-client/tree/develop
