### ISSUE TITLE
Merge this repo with casbin-server

### ISSUE THREAD

**Issue by anton-khodak** [casbin/casbin-go-client#3]
I see this client being just an example of how to interact with casbin-server, I think it can be simply included into the `examples` section of casbin-server without being split to a separate repository. What do you think?

**Comment by hsluoyz** [comment]
This client is not just an example. It's the client side for Casbin Server. I think nobody wants to git pull the whole Casbin Server if he only wants to use the client. Casbin Server (the server side) is much heavier than the client side.

And we may have clients in other languages too, like casbin-java-client, casbin-python-client. We can't put all of them into Casbin Server.

**Comment by hsluoyz** [comment]
Here's the PHP client, although it's still in development.
