### ISSUE TITLE
do you plan to extend this package to allow full casbin-server api

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin-go-client#5]
for example add rbac role manager api

**Comment by hsluoyz** [comment]
Hi @nodece can we do this?

**Comment by nodece** [comment]
@hsluoyz Should add manager api to client.

**Comment by hsluoyz** [comment]
Hi @vtolstov , we want to do this. Can you send PR about it?

**Comment by hsluoyz** [comment]
@vtolstov any update?

**Comment by vtolstov** [comment]
> @vtolstov any update?

sorry, don't have time for this now =(

**Comment by hsluoyz** [comment]
@closetool
